
framework:
    charset:       UTF-8
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    true
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        lifetime:       3600
        auto_start:     true
    secret: xxxxxxxxx # you may change it

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

